/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tstordyallison_ffmpegmr_Merger */

#ifndef _Included_com_tstordyallison_ffmpegmr_Merger
#define _Included_com_tstordyallison_ffmpegmr_Merger
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tstordyallison_ffmpegmr_Merger
 * Method:    initWithOutputStream
 * Signature: (Lorg/apache/hadoop/fs/FSDataOutputStream;)V
 */
JNIEXPORT void JNICALL Java_com_tstordyallison_ffmpegmr_Merger_initWithOutputStream
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_tstordyallison_ffmpegmr_Merger
 * Method:    addSegment
 * Signature: ([BJJ)V
 */
JNIEXPORT void JNICALL Java_com_tstordyallison_ffmpegmr_Merger_addSegment___3BJJ
  (JNIEnv *, jobject, jbyteArray, jlong, jlong);

/*
 * Class:     com_tstordyallison_ffmpegmr_Merger
 * Method:    addSegment
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_tstordyallison_ffmpegmr_Merger_addSegment__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tstordyallison_ffmpegmr_Merger
 * Method:    closeOutput
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tstordyallison_ffmpegmr_Merger_closeOutput
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
