/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tstordyallison_ffmpegmr_Remuxer */

#ifndef _Included_com_tstordyallison_ffmpegmr_Remuxer
#define _Included_com_tstordyallison_ffmpegmr_Remuxer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tstordyallison_ffmpegmr_Remuxer
 * Method:    muxChunks
 * Signature: (Ljava/lang/Iterable;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_tstordyallison_ffmpegmr_Remuxer_muxChunks
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
