/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tstordyallison_ffmpegmr_Demuxer */

#ifndef _Included_com_tstordyallison_ffmpegmr_Demuxer
#define _Included_com_tstordyallison_ffmpegmr_Demuxer
#ifdef __cplusplus
extern "C" {
#endif
#undef com_tstordyallison_ffmpegmr_Demuxer_AVMEDIA_TYPE_UNKNOWN
#define com_tstordyallison_ffmpegmr_Demuxer_AVMEDIA_TYPE_UNKNOWN -1L
#undef com_tstordyallison_ffmpegmr_Demuxer_AVMEDIA_TYPE_VIDEO
#define com_tstordyallison_ffmpegmr_Demuxer_AVMEDIA_TYPE_VIDEO 0L
#undef com_tstordyallison_ffmpegmr_Demuxer_AVMEDIA_TYPE_AUDIO
#define com_tstordyallison_ffmpegmr_Demuxer_AVMEDIA_TYPE_AUDIO 1L
#undef com_tstordyallison_ffmpegmr_Demuxer_AVMEDIA_TYPE_DATA
#define com_tstordyallison_ffmpegmr_Demuxer_AVMEDIA_TYPE_DATA 2L
#undef com_tstordyallison_ffmpegmr_Demuxer_AVMEDIA_TYPE_SUBTITLE
#define com_tstordyallison_ffmpegmr_Demuxer_AVMEDIA_TYPE_SUBTITLE 3L
#undef com_tstordyallison_ffmpegmr_Demuxer_AVMEDIA_TYPE_ATTACHMENT
#define com_tstordyallison_ffmpegmr_Demuxer_AVMEDIA_TYPE_ATTACHMENT 4L
#undef com_tstordyallison_ffmpegmr_Demuxer_AVMEDIA_TYPE_NB
#define com_tstordyallison_ffmpegmr_Demuxer_AVMEDIA_TYPE_NB 5L
/*
 * Class:     com_tstordyallison_ffmpegmr_Demuxer
 * Method:    initDemuxWithFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_tstordyallison_ffmpegmr_Demuxer_initDemuxWithFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tstordyallison_ffmpegmr_Demuxer
 * Method:    initDemuxWithStream
 * Signature: (Ljava/io/InputStream;)I
 */
JNIEXPORT jint JNICALL Java_com_tstordyallison_ffmpegmr_Demuxer_initDemuxWithStream
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_tstordyallison_ffmpegmr_Demuxer
 * Method:    getStreamCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_tstordyallison_ffmpegmr_Demuxer_getStreamCount
  (JNIEnv *, jobject);

/*
 * Class:     com_tstordyallison_ffmpegmr_Demuxer
 * Method:    getStreamData
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_tstordyallison_ffmpegmr_Demuxer_getStreamData
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_tstordyallison_ffmpegmr_Demuxer
 * Method:    getNextChunkImpl
 * Signature: ()Lcom/tstordyallison/ffmpegmr/DemuxPacket;
 */
JNIEXPORT jobject JNICALL Java_com_tstordyallison_ffmpegmr_Demuxer_getNextChunkImpl
  (JNIEnv *, jobject);

/*
 * Class:     com_tstordyallison_ffmpegmr_Demuxer
 * Method:    getStreamMediaTypeRaw
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_tstordyallison_ffmpegmr_Demuxer_getStreamMediaTypeRaw
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_tstordyallison_ffmpegmr_Demuxer
 * Method:    getDurationMs
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_tstordyallison_ffmpegmr_Demuxer_getDurationMs
  (JNIEnv *, jobject);

/*
 * Class:     com_tstordyallison_ffmpegmr_Demuxer
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_tstordyallison_ffmpegmr_Demuxer_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
