/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tstordyallison_ffmpegmr_Transcoder */

#ifndef _Included_com_tstordyallison_ffmpegmr_Transcoder
#define _Included_com_tstordyallison_ffmpegmr_Transcoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tstordyallison_ffmpegmr_Transcoder
 * Method:    initWithBytes
 * Signature: (JJ[J[BDDII)I
 */
JNIEXPORT jint JNICALL Java_com_tstordyallison_ffmpegmr_Transcoder_initWithBytes
  (JNIEnv *, jobject, jlong, jlong, jlongArray, jbyteArray, jdouble, jdouble, jint, jint);

/*
 * Class:     com_tstordyallison_ffmpegmr_Transcoder
 * Method:    getNextPacket
 * Signature: ()Lcom/tstordyallison/ffmpegmr/DemuxPacket;
 */
JNIEXPORT jobject JNICALL Java_com_tstordyallison_ffmpegmr_Transcoder_getNextPacket
  (JNIEnv *, jobject);

/*
 * Class:     com_tstordyallison_ffmpegmr_Transcoder
 * Method:    getStreamData
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_tstordyallison_ffmpegmr_Transcoder_getStreamData
  (JNIEnv *, jobject);

/*
 * Class:     com_tstordyallison_ffmpegmr_Transcoder
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_tstordyallison_ffmpegmr_Transcoder_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
