/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tstordyallison_ffmpegmr_Demuxer_AVMediaType */

#ifndef _Included_com_tstordyallison_ffmpegmr_Demuxer_AVMediaType
#define _Included_com_tstordyallison_ffmpegmr_Demuxer_AVMediaType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
