/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tstordyallison_ffmpegmr_Demuxer */

#ifndef _Included_com_tstordyallison_ffmpegmr_Demuxer
#define _Included_com_tstordyallison_ffmpegmr_Demuxer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tstordyallison_ffmpegmr_Demuxer
 * Method:    initDemuxWithFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_tstordyallison_ffmpegmr_Demuxer_initDemuxWithFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tstordyallison_ffmpegmr_Demuxer
 * Method:    initDemuxWithStream
 * Signature: (Ljava/io/InputStream;)I
 */
JNIEXPORT jint JNICALL Java_com_tstordyallison_ffmpegmr_Demuxer_initDemuxWithStream
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_tstordyallison_ffmpegmr_Demuxer
 * Method:    getStreamData
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_tstordyallison_ffmpegmr_Demuxer_getStreamData
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_tstordyallison_ffmpegmr_Demuxer
 * Method:    getNextChunkImpl
 * Signature: ()Lcom/tstordyallison/ffmpegmr/Demuxer/DemuxPacket;
 */
JNIEXPORT jobject JNICALL Java_com_tstordyallison_ffmpegmr_Demuxer_getNextChunkImpl
  (JNIEnv *, jobject);

/*
 * Class:     com_tstordyallison_ffmpegmr_Demuxer
 * Method:    getStreamCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_tstordyallison_ffmpegmr_Demuxer_getStreamCount
  (JNIEnv *, jobject);

/*
 * Class:     com_tstordyallison_ffmpegmr_Demuxer
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_tstordyallison_ffmpegmr_Demuxer_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
