/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tstordyallison_ffmpegmr_Demuxer_DemuxPacket */

#ifndef _Included_com_tstordyallison_ffmpegmr_Demuxer_DemuxPacket
#define _Included_com_tstordyallison_ffmpegmr_Demuxer_DemuxPacket
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tstordyallison_ffmpegmr_Demuxer_DemuxPacket
 * Method:    deallocData
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_tstordyallison_ffmpegmr_Demuxer_00024DemuxPacket_deallocData
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
