#!/bin/bash

export CLASSPATH="/Users/tom/Code/fyp/ffmpeg-mr/ffmpeg-mr/:/Users/tom/Dropbox/Code/.metadata/.plugins/com.amazonaws.eclipse.sdk/SDK/1.3.3/lib/*:/Users/tom/Dropbox/Code/.metadata/.plugins/com.amazonaws.eclipse.sdk/SDK/1.3.3/third-party/*:/Users/tom/Code/fyp/Dependencies/hadoop-0.20.203.0/hadoop-core-0.20.203.0.jar:/Users/tom/Code/fyp/Dependencies/hadoop-0.20.203.0/lib/*:/Users/tom/Code/fyp/Dependencies/joda-time-2.0/*:/Users/tom/Code/fyp/Dependencies/mrunit-0.8.0-incubating/*:/Users/tom/Code/fyp/ffmpeg-mr/ffmpeg-mr/lib/*"
LIBPATH=-"Djava.library.path=/Users/tom/Code/fyp/ffmpeg-mr/ffmpeg-mr/"

if [ "$1" = "" ]
then
  echo "Usage: $0 <fmr-class> [params...]"
  exit
fi

java -Xdock:name="FFmpeg-MR" -Xmx2048m -Djava.security.krb5.realm=OX.AC.UK -Djava.security.krb5.kdc=kdc0.ox.ac.uk:kdc1.ox.ac.uk $LIBPATH com.tstordyallison.ffmpegmr.$1 $2 $3 $4 $5 $6 $7 $8