/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Transcoder */

#ifndef _Included_Transcoder
#define _Included_Transcoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Transcoder
 * Method:    verifyCodecs
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_Transcoder_verifyCodecs
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
